[package]
name = "webrust"
version = "1.0.0"
edition = "2021"
authors = ["gdubard <infodgjl@gmail.com>"]
description = "Python-like Rust for Web Applications - A bridge between Python simplicity and Rust power"
documentation = "https://docs.rs/webrust"
repository = "https://github.com/gerarddubard/webrust"
homepage = "https://github.com/gerarddubard/webrust"
license = "MIT"
keywords = ["python", "web", "gui", "latex", "formatting"]
categories = ["gui", "web-programming", "development-tools"]
readme = "README.md"

[dependencies]
tiny_http = "0.12.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
lazy_static = "1.5.0"
webrust-macros = { version = "1.0.0", path = "webrust-macros" }


[features]
default = []

[[example]]
name = "simpleio"
path = "examples/py_simpleio.rs"

[[example]]
name = "advancedio"
path = "examples/py_advancedio.rs"

[[example]]
name = "string"
path = "examples/py_string.rs"

[[example]]
name = "utils"
path = "examples/py_utils.rs"

[[example]]
name = "table"
path = "examples/py_table.rs"

[[example]]
name = "chart"
path = "examples/py_chart.rs"

[workspace]
members = ["webrust-macros"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]